# Generated by Django 4.1 on 2022-08-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_product_product_desc_product_product_disc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_disc',
        ),
        migrations.AddField(
            model_name='product',
            name='product_desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
