# Generated by Django 4.1 on 2022-09-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_whislist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='whislist',
            new_name='Wishlist',
        ),
    ]
