# Generated by Django 4.1 on 2022-09-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_cart_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Accessories', 'Accessories'), ('Camera', 'camera'), ('Smartphone', 'Smartphone')], max_length=100),
        ),
    ]
